module.exports = [
  {
    upload_id: "1",
    owner_id: "1",
    liked_by: JSON.stringify([]),
    title: "Rubber Plant",
    description: "This needs lots of indirect light! It's also propagatable.",
    image_url: "photo-1562351757-66f3589f30cf.jpg",
  },
  {
    upload_id: "2",
    owner_id: "2",
    liked_by: JSON.stringify([]),
    title: "Eucalyptus",
    description: "Give your space a relaxing scent :)",
    image_url: "photo-1546387903-6d82d96ccca6.jpg",
  },
  {
    upload_id: "3",
    owner_id: "3",
    liked_by: JSON.stringify([]),
    title: "Succulent",
    description: "iz very cute :3",
    image_url: "photo-1506637066753-de610c8b0cab.jpg",
  },
  {
    upload_id: "4",
    owner_id: "4",
    liked_by: JSON.stringify([]),
    title: "Aloe Vera",
    description: "Health plant with many uses. Water twice a month",
    image_url: "photo-1569745358610-b01866003860.jpg",
  },
  {
    upload_id: "5",
    owner_id: "5",
    liked_by: JSON.stringify([]),
    title: "Venus Fly Trap",
    description: "Rare species in need of a warm, humid environment",
    image_url: "photo-1531323423421-1c190b0fa2ce.jpg",
  },
  {
    upload_id: "6",
    owner_id: "6",
    liked_by: JSON.stringify([]),
    title: "Monstera",
    description: "I don't have room for this!",
    image_url: "photo-1546381061-3e57f7cc61fd.jpg",
  },
  {
    upload_id: "7",
    owner_id: "7",
    liked_by: JSON.stringify([]),
    title: "Fig Tree",
    description: "You get a plant clipping to propagate",
    image_url: "photo-1453904300235-0f2f60b15b5d.jpg",
  },
  {
    upload_id: "8",
    owner_id: "8",
    liked_by: JSON.stringify([]),
    title: "Cactus",
    description: "My daughter doesn't like it :/",
    image_url: "photo-1586323538904-4dff5de33989.jpg",
  },
  {
    upload_id: "9",
    owner_id: "9",
    liked_by: JSON.stringify([]),
    title: "Pilea",
    description: "AKA chinese money plant for that good feng shui",
    image_url: "photo-1590417975638-1f8d37cf22df.jpg",
  },
];
