module.exports = [
  {
    upload_id: "1",
    owner_id: "1",
    liked_by: JSON.stringify([]),
    title: "",
    description: "",
    image_path: "",
  },
  {
    upload_id: "2",
    owner_id: "2",
    liked_by: JSON.stringify([]),
    title: "",
    description: "",
    image_path: "",
  },
  {
    upload_id: "3",
    owner_id: "3",
    liked_by: JSON.stringify([]),
    title: "",
    description: "",
    image_path: "",
  },
  {
    upload_id: "4",
    owner_id: "4",
    liked_by: JSON.stringify([]),
    title: "",
    description: "",
    image_path: "",
  },
  {
    upload_id: "5",
    owner_id: "5",
    liked_by: JSON.stringify([]),
    title: "",
    description: "",
    image_path: "",
  },
  {
    upload_id: "6",
    owner_id: "6",
    liked_by: JSON.stringify([]),
    title: "",
    description: "",
    image_path: "",
  },
  {
    upload_id: "7",
    owner_id: "7",
    liked_by: JSON.stringify([]),
    title: "",
    description: "",
    image_path: "",
  },
  {
    upload_id: "8",
    owner_id: "8",
    liked_by: JSON.stringify([]),
    title: "",
    description: "",
    image_path: "",
  },
  {
    upload_id: "9",
    owner_id: "9",
    liked_by: JSON.stringify([]),
    title: "",
    description: "",
    image_path: "",
  },
];
