module.exports = [
  {
    user_id: "1",
    name: "ironman",
    email: "ironman@protonmail.com",
    likes: JSON.stringify([]),
    upload_ids: JSON.stringify(["1"]),
  },
  {
    user_id: "2",
    name: "thor",
    email: "thor@asgard.com",
    likes: JSON.stringify([]),
    upload_ids: JSON.stringify(["2"]),
  },
  {
    user_id: "3",
    name: "captain america",
    email: "capt@america.us",
    likes: JSON.stringify([]),
    upload_ids: JSON.stringify(["3"]),
  },
  {
    user_id: "4",
    name: "black widow",
    email: "natasha@blackwidow.io",
    likes: JSON.stringify([]),
    upload_ids: JSON.stringify(["4"]),
  },
  {
    user_id: "5",
    name: "dr strange",
    email: "strangedoctor@me.com",
    likes: JSON.stringify([]),
    upload_ids: JSON.stringify(["5"]),
  },
  {
    user_id: "6",
    name: "hulk",
    email: "noanger@harmony.com",
    likes: JSON.stringify([]),
    upload_ids: JSON.stringify(["6"]),
  },
  {
    user_id: "7",
    name: "black panther",
    email: "4eva@wakanda.org",
    likes: JSON.stringify([]),
    upload_ids: JSON.stringify(["7"]),
  },
  {
    user_id: "8",
    name: "spiderman",
    email: "peterparker@midtown.edu",
    likes: JSON.stringify([]),
    upload_ids: JSON.stringify(["8"]),
  },
  {
    user_id: "9",
    name: "r2d2",
    email: "beepboopbeep@astromech.sw",
    likes: JSON.stringify([]),
    upload_ids: JSON.stringify(["9"]),
  },
];
